### PR TITLE
User-Interface/upload-status-clarity

### LINKED ISSUE #111: Green circle with question mark is meaningless to users
After upload, sometimes users are presented with a green circle containing a question mark as a status. Users have no idea what this means (I'll tell you)...

Meaning: at this stage, file is in FMS storage, but not searchable by FMS. Metadata is being transformed and surfaced to FMS. This happens on a queue, and sometimes can take weeks to catch up. A user NEVER has to worry at this point.

This process should be made more visible/understandable to users. 

Icon should be changed so that it is a light green (#CEE9DF) with a checkmark. [Follow these designs](https://www.figma.com/design/uOgQ3a9MUk2BCQrEAfw8jZ/File-Upload-App?node-id=404-2251&t=m0zDkRW64x0prMc6-1)

Upon hover, a tooltip should say: "File successfully uploaded to FMS. It will searchable once all metadata has been appended, which is happening now in the background"

### PR DESCRIPTION
**Pull request by BrianWhitneyAI**
### Description 
Attempts to resolve #111 After upload, sometimes users are presented with a green circle containing a question mark as a status. Users have no idea what this means. We decided to move the question mark to a check mark and change the color. Following this spec:
Screenshot 2024-10-29 at 2 08 08 PM

### CODE REVIEW

**Comment by BrianWhitneyAI** [comment]
Current Appearance: 
Screenshot 2024-10-29 at 2 06 43 PM
Screenshot 2024-10-29 at 2 06 37 PM

**Review by TravisKroeker — CHANGES_REQUESTED** [review]
Please update the tooltip for added clarity for the users. It should read:

"File successfully uploaded to FMS. It will be searchable once all metadata has been appended, which is happening now in the background"

**Review by SeanLeRoy — APPROVED** [review]

**Comment by BrianWhitneyAI** [comment]
> Please update the tooltip for added clarity for the users. It should read:
> 
> "File successfully uploaded to FMS. It will be searchable once all metadata has been appended, which is happening now in the background"

Totally missed this. Some questions here. Do we want to merge the message we are showing for these two conditions
```
    if (etlProcess?.status === JSSJobStatus.FAILED) {
      tooltip = `${tooltip} - File successfully uploaded to FMS. It will be searchable once all metadata has been appended, which is happening now in the background`;
    } else if (etlProcess?.status !== JSSJobStatus.SUCCEEDED) {
      tooltip = `${tooltip} - File successfully uploaded to FMS. Working on making it visible in the File Upload App if it isn't already`;
    }
```

**Comment by SeanLeRoy** [comment]
> > Please update the tooltip for added clarity for the users. It should read:
> > "File successfully uploaded to FMS. It will be searchable once all metadata has been appended, which is happening now in the background"
> 
> Totally missed this. Some questions here. Do we want to merge the message we are showing for these two conditions
> 
> ```
>     if (etlProcess?.status === JSSJobStatus.FAILED) {
>       tooltip = `${tooltip} - File successfully uploaded to FMS. It will be searchable once all metadata has been appended, which is happening now in the background`;
>     } else if (etlProcess?.status !== JSSJobStatus.SUCCEEDED) {
>       tooltip = `${tooltip} - File successfully uploaded to FMS. Working on making it visible in the File Upload App if it isn't already`;
>     }
> ```

This was a thing because I thought that maybe it was actionable if the ETL failed to process the file. However, now that you are calling this out I'm realizing there really isn't anything they could do & we should either a) be comfortable enough with our system and error alerting to assume this will pop up elsewhere or b) make option a thing rather than burdening the user with worry

**Comment by TravisKroeker** [comment]
In my user research, users didn't understand what "making it visible" to different apps meant. They just want to know a) why isn't it "fully uploaded" with a bright green check, and b) do I need to do anything further to make sure it gets uploaded?

In my conversations with Chris and Tyler, they explained that at this stage in the process, the upload is complete, but  FMS is collating metadata from various sources before the file is able to be shown to users on FMS. I also understood that at this step, the user never really has to worry about their upload "failing" anymore.

If all of that is true, then the tooltip should focus on a) reassuring the user that the upload was successful and is now complete, b) reassuring the user they do not need to perform any other actions, and c) explain to them why they may not see their upload in FMS yet

**Review by TravisKroeker — APPROVED** [review]

**Pull request merged**
