### PR TITLE
Feature/swe 236 fua max chunk

### PR DESCRIPTION
**Pull request by kmitcham**
This is my first commit to FUA, so I may be doing something wrong, even with my code supplied by a smart person.

### CODE REVIEW

**Comment by SeanLeRoy** [comment]
We are basing the FSS2 stuff off a branch called `main-fss2`, could you target this PR to that branch instead?

**Review by SeanLeRoy — APPROVED** [review]

**Comment by kmitcham** [comment]
I see I'm allowed to commit with one review; what is the standard here?

**Comment by SeanLeRoy** [comment]
> I see I'm allowed to commit with one review; what is the standard here?

This is because `main-fss2` has no branch protection rules. Just `main` does.

**Review by pgarrison — APPROVED** [review]
Looks good to me! If I'm understanding right, FSS2 tells the client what chunk size to use, which may be over 40MB. In that case, we'll upload a single arbitrarily large chunk at a time. What size chunks are we using?

**Comment by kmitcham** [comment]
> 

Currently our chunksized is based on a fairly arbitrary constant, increased once the file is more than 10K * chunk-size.  
src/main/resources/application.properties:file.chunksize.optimized=8000000

**Review by hughes036 — APPROVED** [review]

**Pull request merged**
